/**
 * @description define the navigation routes name by key
 */
export const Routes: {[key: string]: string} = {
  Login: 'Login',
  Intro: 'Intro',
  Welcome: 'Welcome',
  Home: 'Home',
  Account: 'Account',
  Register: 'Register',
  ResetPassword: 'ResetPassword',
  PreLogin: 'PreLogin',
  ConfirmOTP: 'ConfirmOTP',
  ChangePassword: 'ChangePassword',
  ForgotPassword: 'ForgotPassword',
  ForgotUserName: 'ForgotUserName',
  MyRequest: 'MyRequest',
  MyRequestOverView: 'MyRequestOverView',
  ApprovalCenter: 'ApprovalCenter',
  Main: 'Main',
  Profile: 'Profile',
  ProfileEdit: 'ProfileEdit',
  Security: 'Security',
  HelpCenter: 'HelpCenter',
  SummaryList: 'SummaryList',
  Notification: 'Notification',
  ProfileInformation: 'ProfileInformation',
  FAQ: 'FAQ',
  TermConditions: 'TermConditions',
  PrivacyPolicy: 'PrivacyPolicy',
  AboutUs: 'AboutUs',
  Congration: 'Congration',
  PendingOverView: 'PendingOverView',
  ApprovedOverView: 'ApprovedOverView',
  PendingHistory: 'PendingHistory',
  CreateRequest: 'CreateRequest',
  NewRequest: 'NewRequest',
  EditRequest: 'EditRequest',
  OverViewNewRequest: 'OverViewNewRequest',
  MyRequestHistory: 'MyRequestHistory',
};
